<?php

namespace Inkl\AddressUtils;

class StreetSplitterTest extends \PHPUnit_Framework_TestCase
{

	/** @var StreetSplitter */
	private $streetSplitter;

	protected function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		$this->streetSplitter = new StreetSplitter();
	}

	/**
	 * @dataProvider testSplitDataProvider
	 * @param string $street
	 * @param array $expected
	 */
	public function testSplit($street, $expected)
	{
		$this->assertSame($expected, $this->streetSplitter->split($street));
	}

	public function testSplitDataProvider()
	{
		return [
			['Straße 1', ['Straße', '1']],
			['Straße 1a', ['Straße', '1a']],
			['Straße 1 a', ['Straße', '1a']],
			['Straße', ['Straße', '-']],
			['Neue Straße ', ['Neue Straße', '-']],
			['Neue Straße 32 ', ['Neue Straße', '32']],
		];
	}

}